import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>{children}</body>
            {/* page.js가 return한 값이 children자리에 온다 */}
        </html>
    );
}
