// "use client";

import Link from "next/link";
import "./globals.css";
// import { useEffect, useState } from "react";

// export const metadata = {
//     title: "Web Tutorials",
//     description: "Generated by lucia",
// };

export default async function RootLayout({ children }) {
    // const [topics, setTopics] = useState([]);
    // useEffect(() => {
    // fetch("http://localhost:9999/topics")
    //     .then((res) => res.json())
    //     .then((result) => {
    //         setTopics(result);
    //     });
    // }, []);

    // npx json-server --port 9999 --watch db.json
    // 상기의 명령어로 json-server를 실행 => db.json 파일이 생성되고 수정도 가능 => 거기서 데이터를 받아옴
    const resp = await fetch("http://localhost:9999/topics", {
        cache: "no-store",
    });
    const topics = await resp.json();

    return (
        <html>
            <body>
                <h1>
                    <Link href="/">WEB</Link>
                </h1>
                <ol>
                    {topics.map((topic) => {
                        return (
                            <li key={topic.id}>
                                <Link href={`/read/${topic.id}`}>
                                    {topic.title}
                                </Link>
                            </li>
                        );
                    })}
                </ol>
                {children}
                <ul>
                    <li>
                        <Link href="/create">Create</Link>
                    </li>
                    <li>
                        <Link href="/update/1">Update</Link>
                    </li>
                    <li>
                        <input type="button" value={"delete"} />
                    </li>
                </ul>
            </body>
            {/* page.js가 return한 값이 children자리에 온다 */}
        </html>
    );
}
